import { ethers } from "ethers"
import Head from "next/head"
import { useState } from "react"
import styles from "../styles/Home.module.css"

const Home = () => {
  const [walletAddress, setWalletAddress] = useState("no address detected!")

  const requestAccount = async () => {
    if (window.ethereum) {
      console.log("Metamask!")

      try {
        const accounts = await window.ethereum.request({
          method: "eth_requestAccounts",
        })
        setWalletAddress(accounts[0])
      } catch (error) {
        console.log("error connecting ...")
      }
    } else console.log("No Metamask!")
  }

  const connectWallet = async () => {
    if (typeof window.ethereum !== "undefined") {
      await requestAccount()

      const provider = new ethers.providers.Web3Provider(window.ethereum)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Next.js Application</h1>
        <button onClick={requestAccount}>Connect Wallet</button>
        <h3>Connected with address: {walletAddress}</h3>
      </main>

      <footer className={styles.footer}>
        <h4>Footer</h4>
      </footer>
    </div>
  )
}

export default Home
